version: 2
jobs:
  # Build project
  build:
    docker:
      - image: circleci/node:8.11
    environment:
      - NODE_ENV: development
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  # Test project
  test:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm test

# Config flows excute project
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master